title: Lucas N. Ribeiro
author: Lucas N. Ribeiro
#email: your-email@example.com
description: Lucas N. Ribeiro's personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lnribeiro.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: America/Fortaleza

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# Google Analytics
google_analytics: UA-124242145-1